baseURL: 'https://www.nathanstates.com/'
theme: hugo-apero
languageCode: en
title: NS 
author: Nathan States
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: ""
    noClasses: no
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: 'nathan-hex'
  customtextFontFamily: '' 
  customheadingFontFamily: ''
  textFontFamily: 'georgia'
  headingFontFamily: 'georgia'
  description: Personal Blog. 
  mainSections: 
    - blog
    - dashboards 
    - series
  math:
    renderer: katex
  navallcaps: no
  orgLocal: Anywhere 
  orgName: RStudio
  show_post_thumbnail: no
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/Nathan-States
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/nathanstates_
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
  socialInFooter: yes
  socialInHeader: yes
  theme: ""
  twitter: twitter
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: Nathan-States/site
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
  header:
    - name: About
      url: /about/
      weight: 99
    - name: Blog
      url: /blog/
      weight: 1
    - name: Dashboards
      url: /dashboards/
      weight: 2
    - name: Series
      url: /series/
      weight: 3
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
